sudo: required
services:
  - docker
env:
  global:
    - GIT_SHA=$(git rev-parse HEAD)
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1
before_install:
  - openssl aes-256-cbc -K $encrypted_ba9c725aa318_key -iv $encrypted_ba9c725aa318_iv -in udemy-k8s-1212-cf34cb3aa3db.json.enc -out udemy-k8s-1212-cf34cb3aa3db.json -d
  - curl https://sdk.cloud.google.com | bash > /dev/null;
  - source $HOME/google-cloud-sdk/path.bash.inc
  - gcloud components update kubectl
  - gcloud auth activate-service-account --key-file udemy-k8s-1212-cf34cb3aa3db.json
  - gcloud config set project udemy-k8s-1212
  - gcloud config set compute/zone europe-west3-a
  - gcloud container clusters get-credentials multi-cluster
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t andreasgrob/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true andreasgrob/react-test npm test

deploy:
  provider: script
  script: bash ./deploy.sh
  on:
    branch: main
